### ISSUE TITLE
AccessDeniedExceptions on clean startup of CDMI server

### ISSUE THREAD

**Issue by anupash** [indigo-dc/CDMI#51]
See the full logs here

[https://gist.github.com/anupash/c6996a827d97c3a99dd02ac391d7781c](https://gist.github.com/anupash/c6996a827d97c3a99dd02ac391d7781c)

Before starting the CDMI server, I cleaned the cdmi_\* and .cdmi_\* directories.

The errors also happen on an dirty boot (without deleting the metadata directories cdmi_\* and .cdmi_*).

**Comment by anupash** [comment]
Not happening on clean boot, when the cdmi-baseDirectory is outside NFS mount of dCache.

**Comment by bertl4398** [comment]
seems to me like a file system permissions problem on your side

**Comment by anupash** [comment]
I have thoroughly verified all the user and group permissions on the NFS mount and they are all fine, but still get this error. 

Have you verified that CDMI server behaves correctly when the cdmi-baseDirectory is on NFS mounts of other systems (not dCache)?

**Comment by paulmillar** [comment]
This looks like a problem where the CDMI server assumes that an existing file may be modified.

This assumption doesn't hold for dCache: once a file is written it may not be modified.

In any case, modifying an existing file is not a good solution: better would be to create a new file and rename it to overwrite the existing file: such operations are atomic, under POSIX.  Since overwriting content is supported by dCache, fixing this racy rewrite of the content would (likely) also fix the problem for dCache.

**Comment by bertl4398** [comment]
try with the latest commit on the master branch .. if this doesn't fix it feel free to reopen
